spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://todo-database.crq6ushdq95z.ap-northeast-2.rds.amazonaws.com:3306/TodoList?serverTimezone=Asia/Seoul
    username: SeongJun
    password: tjdwns144
    #url: jdbc:mysql://localhost:3306/todolist?serverTimezone=Asia/Seoul
    #username: root
    #password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
